dist: xenial
language: csharp
mono: none
dotnet: 2.2.203
addons:
  apt:
    packages:
      - powershell
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_install:
  - export PATH=$HOME/.dotnet/tools:$PATH
script:
  - pwsh ./test.ps1
after_success:
  - bash <(curl -s https://codecov.io/bash)
  cache:
  directories:
    - $HOME/.nuget/packages
    - $HOME/.dotnet/tools
