name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.101"

      - name: Run tests in each folder
        run: |
          for dir in */; do
            if [ -f "$dir/$dir.csproj" ]; then
              echo "Running tests in $dir"
              cd "$dir"
              dotnet test
              cd ..
            fi
          done

